### PR TITLE
ViStart v8.1.5255

### PR DESCRIPTION
**Pull request by GeorgeK1ng**
- Improved translations, every visible element under Windows XP host can be now translated using Language.xml
- Added new translatable elements into all available languages
- Added Czech.xml
- Added new context menu in NavigationPane on custom items - Open, Rename and Hide
- Added new context menu to "Computer" - Manage, Search
- Added new context menu to "Computer" / "Network" / "Control Panel" - Show on desktop / Hide from desktop
- Added new context menu "Explore" when browsing All programs to be able open whole folder
- Removed ViPad context menu when ViPad is not running or not installed. No more "online" feature in context menu
- Removed More themes and More Orbs online buttons. No more "online" features from Settings
- Realigned buttons on Style configuration page
- Realigned elemens on About page and added current build visibility
- Updated settings.xml with new defaults
- Fixed "No skins available", if doesn't exist %APPDATA%\ViStart use current EXE dir if _skins folder exist there

Known bugs:
1) When using Start search "Files" string can't be translated right now, I can't find correct place to replace this string with Language related string saved as "StrFiles" in Language.xml 
2) NavigationPane font color is always white, this needs to be solved and enable some kind of Font Color option into layout.xml  - **this is already here, nothing to investigate**
3) When using Right click on "Run..." StartMenu keeps open and Run dialogbox is not on correct place

### CODE REVIEW

**Comment by GeorgeK1ng** [comment]
Here you can see translations improvements

ViStart_Tr01
ViStart_Tr02
ViStart_Tr03
ViStart_Tr04
ViStart_Tr05
ViStart_Tr06

Here is last remaining "Files" word that needs to be mapped to "StrFiles". Hope you can find cause of this "non-translatable" item
ViStart_Tr07

And here is demostrated needs of colorized font in NavigationPane. As you can see, it's really badly visible white font on Blue background. I would like to see option in layout.xml. But I was unable to find correct place where I can specify font color for Navigation pane items
ViStart_Tr_F1


P.S. Code for context menu is not clear at all, but works

**Comment by lee-soft** [comment]
I think the "Files" is actually a bitmap in the "Vistart.RES". I was meaning to change this some day to be actual text. You might need to open ViStart.RES with ResHacker to change it for yourself

I will have a look at these changes over the weekend. Thanks for contributing

**Review by lee-soft — CHANGES_REQUESTED** [review]
some of the language files (The ones marked as binary) have strange Chinese characters in them

For example Brazilian looks like this
image

**Comment by GeorgeK1ng** [comment]
I have uploaded Brazilian.xml again right now

**Comment by GeorgeK1ng** [comment]
I have reuploaded whole ViStart Source tree grabbed from XP machine. 

+ I have added Show on desktop / Hide from desktop context menu for Network and Control panel. Desktop refresh is now added after registry touch so Computer and Network icons are now "real-time" Showed or Hidden.
+ Forgotten ""Shutdown" text was fixed and now is correctly translated

ViStart.RES doesn't contain any BMP / PNG with "Files" caption for Start Search. I have currently no idea where is hardcoded "Files" string. Hope you can find it out to make 100% strings translatable

So still these 2 bugs are there
1) "Files" string is not loaded from translation file
2) Start menu keeps open and Run dialog box is not placed correctly when right click on Run... and use context menu Run...

**Review by lee-soft — CHANGES_REQUESTED** [review]
If you checkout the PR to your local machine you can see the language files still have Chinese text in them. The following language files are affected

Brazilian.xml
Italian.xml
German.xml
Dutch.xml
Czech.xml
English.xml
Korean.xml

image

French and Spanish don't seem to have this issue. Try to use a modern text editor like Notepad++. You can see by checking the size of the language files, they should be 6KB but the ones with strange characters in them are in fact 12KB. 

image

The file type in Notepad++ should be
Windows (CR LF), UTF-8-BOM. See the bottom of the panel on this screenshot,

image

You can update the type by right clicking it and selecting Windows (CR LF), 

image


GitHUB should not think the file type is "Binary". Note the file changes in this PR. Notice French appears as text but the others appear as 'bin'. 

image

**Comment by lee-soft** [comment]
We can safely ignore whitespace changes, the PR looks bigger than it actually is. On GitHub there is a feature to hide whitespace changes. So do not worry about it

**Comment by GeorgeK1ng** [comment]
Language files seems to be broken as I used your original ones with only adding new elements inside. I have rebuilded right now all of them except Korean as I can't do this one on my XP machine.

**Comment by fediaFedia** [comment]
Glad to see someone is working on ViStart!

Just an FYI, at some point the Windows 11 Compatibility got broken :( 
I used built 5257 here: https://www.deviantart.com/fediafedia/art/Longhorn-2022-ViStart-11-WIP-905330208

**Comment by GeorgeK1ng** [comment]
> Glad to see someone is working on ViStart!
> 
> Just an FYI, at some point the Windows 11 Compatibility got broken :( I used built 5257 here: https://www.deviantart.com/fediafedia/art/Longhorn-2022-ViStart-11-WIP-905330208

Nice to see you here! Maybe you can help me with adapting current themes to ViStart. I have collected various of them on Deviantart, including yours. I will send you more info to e-mail from your profile description. With your help can be ViStart Themes pefrect!

About Windows 11 compatibility, maybe @lee-soft can solve it. Currently This build 5255 is tested on my side only on XP host. In future I will test it under Vista / 7 too to see what else needs to be modded according to full translation support.

**Comment by GeorgeK1ng** [comment]
Reuploaded all languages again, Added incomplete Russian translation from another Fork with all needed strings for 8.1.5255

**Review by lee-soft — APPROVED** [review]
There are some good contributions here 👍

**Pull request merged**
