### PR TITLE
ViStart v8.1.5256

### PR DESCRIPTION
**Pull request by GeorgeK1ng**
**ViStart v8.1.5256**

- Removed "Recent" word from **Skins/Windows 7 Start Menu/startmenu_expanded.png**
- Removed ViStart.manifest
- Added ViStart.exe.manifest
- Updated application icon with older better one from v1.6 era
- Improved "Frequent programs" loading from settings.xml, non existent items are not displayed
- Increased limit from 12 to 17 items in Start Menu "Navigation pane"
- Added Libraries, Downloads, Printers and Faxes, Set Program Access and Defaults support for settings.xml
- Added new default settings.xml into main directory and RES
       - Windows XP related options are defaults
             - Added Downloads folder support (Downloads folder must be placed in CLSID {450D8FBA-AD25-11D0-98A8-0800361B1103} know as My Documents , so this is dynamic for all languages when you create this folder
             - Added Games folder support which points to **%ALLUSERSPROFILE%\Start Menu\Programs\Games** - this is not dynamic and on each XP language you need to manually fix this path in settings.xml if would like to use this option
             - Fixed Help and support option
       - Windows Vista / 7 options Libraries, Downloads, Games, Help are commented out, you need manually fix settings.xml on other systems than XP / 2003
- Added all needed strings to all language files. Fully translated in only Czech.xml until translators finish other languages

NOTE: You can add all 17 unique option into Start Menu. For example default Windows 7 Start Menu skin can display 12 items (Upcoming Windows XP / Vista skins can display 14 items instead). So you need to decide which ones you would like to use

image

image

image

image

image

### CODE REVIEW

**Review by lee-soft — APPROVED** [review]
thanks again for the improvements

**Comment by GeorgeK1ng** [comment]
I can't merge it to your branch as it can do only repo owner even with approved changes. I would create another merge soon with Fixed "strFiles" translation issue

**Comment by lee-soft** [comment]
Do you happen to have discord? We have a development channel. It's on the lee-soft.com home page

**Review by lee-soft — APPROVED** [review]
looks good,

**Pull request merged**
